module.exports = {
	// START va language states
	START: 'START',
	LANGUAGE_SELECTION: 'LANGUAGE_SELECTION',

	// MAIN MENU
	MAIN_MENU: 'MAIN_MENU',

	// DRIVER REGISTRATION STATES
	DRIVER_REG_FROM_REGION: 'DRIVER_REG_FROM_REGION',
	DRIVER_REG_TO_REGION: 'DRIVER_REG_TO_REGION',
	DRIVER_REG_FULLNAME: 'DRIVER_REG_FULLNAME',
	DRIVER_REG_PHONE: 'DRIVER_REG_PHONE',
	DRIVER_REG_SELECT_CAR: 'DRIVER_REG_SELECT_CAR',
	DRIVER_REG_CAR_MODEL: 'DRIVER_REG_CAR_MODEL',
	DRIVER_REG_CAR_TYPE: 'DRIVER_REG_CAR_TYPE',
	DRIVER_REG_CAR_NUMBER: 'DRIVER_REG_CAR_NUMBER',
	DRIVER_EDIT_CAR_NUMBER: 'DRIVER_EDIT_CAR_NUMBER',
	DRIVER_REG_MAX_PASSENGERS: 'DRIVER_REG_MAX_PASSENGERS',
	DRIVER_REG_MAX_PASSENGERS_CUSTOM: 'driver_reg_max_passengers_custom',
	DRIVER_REG_SERVICE_TYPE: 'DRIVER_REG_SERVICE_TYPE',
	DRIVER_REG_WORK_HOURS: 'DRIVER_REG_WORK_HOURS',
	DRIVER_REG_WORK_HOURS_CUSTOM: 'DRIVER_REG_WORK_HOURS_CUSTOM',
	DRIVER_REG_DATE_SELECTION: 'DRIVER_REG_DATE_SELECTION',
	DRIVER_REG_TIME_INPUT: 'DRIVER_REG_TIME_INPUT',
	DRIVER_REG_CONFIRM: 'DRIVER_REG_CONFIRM',

	// PASSENGER STATES
	PASSENGER_FROM_REGION: 'PASSENGER_FROM_REGION',
	PASSENGER_TO_REGION: 'PASSENGER_TO_REGION',
	PASSENGER_COUNT: 'PASSENGER_COUNT',
	PASSENGER_PARCEL: 'PASSENGER_PARCEL',
	PASSENGER_PARCEL_DESC: 'PASSENGER_PARCEL_DESC',
	PASSENGER_COMMENT: 'PASSENGER_COMMENT',
	PASSENGER_CONFIRM: 'PASSENGER_CONFIRM',

	// PASSENGER INFO STATES (YANGI)
	PASSENGER_INFO_NAME: 'PASSENGER_INFO_NAME',
	PASSENGER_INFO_PHONE: 'PASSENGER_INFO_PHONE',

	// DRIVER EDIT STATES
	DRIVER_EDIT_FULLNAME: 'DRIVER_EDIT_FULLNAME',
	DRIVER_EDIT_PHONE: 'DRIVER_EDIT_PHONE',
	DRIVER_EDIT_CAR: 'DRIVER_EDIT_CAR',
	DRIVER_EDIT_PASSENGERS: 'DRIVER_EDIT_PASSENGERS',
	DRIVER_EDIT_ROUTE_FROM: 'DRIVER_EDIT_ROUTE_FROM',
	DRIVER_EDIT_ROUTE_TO: 'DRIVER_EDIT_ROUTE_TO',
	DRIVER_EDIT_SERVICES: 'DRIVER_EDIT_SERVICES',
	DRIVER_EDIT_TIME_DATE: 'DRIVER_EDIT_TIME_DATE',
	DRIVER_REG_CAR_SEARCH: 'DRIVER_REG_CAR_SEARCH',
	DRIVER_REG_DATE_SELECTION: 'driver_reg_date_selection',
	DRIVER_REG_DATE_MANUAL: 'driver_reg_date_manual',
	DRIVER_REG_TIME_INPUT: 'driver_reg_time_input',

	// ADMIN STATES
	ADMIN_MENU: 'ADMIN_MENU',
	ADMIN_ADD_PAYMENT: 'ADMIN_ADD_PAYMENT'
}
