module.exports = {
	// Asosiy holatlar
	START: 'START',
	MAIN_MENU: 'MAIN_MENU',

	// Yo'lovchi holatlari
	PASSENGER_FROM_REGION: 'PASSENGER_FROM_REGION',
	PASSENGER_TO_REGION: 'PASSENGER_TO_REGION',
	PASSENGER_PARCEL: 'PASSENGER_PARCEL',
	PASSENGER_PARCEL_DESC: 'PASSENGER_PARCEL_DESC',
	PASSENGER_COMMENT: 'PASSENGER_COMMENT',
	PASSENGER_CONFIRM: 'PASSENGER_CONFIRM',

	// Haydovchi ro'yxatdan o'tish
	DRIVER_REG_FROM_REGION: 'DRIVER_REG_FROM_REGION',
	DRIVER_REG_TO_REGION: 'DRIVER_REG_TO_REGION',
	DRIVER_REG_FULLNAME: 'DRIVER_REG_FULLNAME',
	DRIVER_REG_PHONE: 'DRIVER_REG_PHONE',
	DRIVER_REG_CAR_MODEL: 'DRIVER_REG_CAR_MODEL',
	DRIVER_REG_CAR_NUMBER: 'DRIVER_REG_CAR_NUMBER',
	DRIVER_REG_SERVICE_TYPE: 'DRIVER_REG_SERVICE_TYPE',
	DRIVER_REG_DEPARTURE_TIME: 'DRIVER_REG_DEPARTURE_TIME',
	DRIVER_REG_CONFIRM: 'DRIVER_REG_CONFIRM',

	// Haydovchi sozlamalari
	DRIVER_MENU: 'DRIVER_MENU',
	DRIVER_EDIT_PROFILE: 'DRIVER_EDIT_PROFILE',
	DRIVER_STATUS: 'DRIVER_STATUS',
	DRIVER_PAYMENT: 'DRIVER_PAYMENT',

	// Admin holatlari
	ADMIN_MENU: 'ADMIN_MENU',
	ADMIN_DRIVER_MANAGE: 'ADMIN_DRIVER_MANAGE',
	ADMIN_ORDER_MANAGE: 'ADMIN_ORDER_MANAGE'
}
